// Rice Search gRPC Service Definition
// Protocol buffer definitions for the Rice Search platform.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: ricesearch.proto

package ricesearchpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiceSearch_Search_FullMethodName             = "/ricesearch.v1.RiceSearch/Search"
	RiceSearch_SearchStream_FullMethodName       = "/ricesearch.v1.RiceSearch/SearchStream"
	RiceSearch_Index_FullMethodName              = "/ricesearch.v1.RiceSearch/Index"
	RiceSearch_IndexBatch_FullMethodName         = "/ricesearch.v1.RiceSearch/IndexBatch"
	RiceSearch_Delete_FullMethodName             = "/ricesearch.v1.RiceSearch/Delete"
	RiceSearch_Sync_FullMethodName               = "/ricesearch.v1.RiceSearch/Sync"
	RiceSearch_Reindex_FullMethodName            = "/ricesearch.v1.RiceSearch/Reindex"
	RiceSearch_GetIndexStats_FullMethodName      = "/ricesearch.v1.RiceSearch/GetIndexStats"
	RiceSearch_ListStores_FullMethodName         = "/ricesearch.v1.RiceSearch/ListStores"
	RiceSearch_CreateStore_FullMethodName        = "/ricesearch.v1.RiceSearch/CreateStore"
	RiceSearch_GetStore_FullMethodName           = "/ricesearch.v1.RiceSearch/GetStore"
	RiceSearch_DeleteStore_FullMethodName        = "/ricesearch.v1.RiceSearch/DeleteStore"
	RiceSearch_GetStoreStats_FullMethodName      = "/ricesearch.v1.RiceSearch/GetStoreStats"
	RiceSearch_Health_FullMethodName             = "/ricesearch.v1.RiceSearch/Health"
	RiceSearch_Version_FullMethodName            = "/ricesearch.v1.RiceSearch/Version"
	RiceSearch_RegisterConnection_FullMethodName = "/ricesearch.v1.RiceSearch/RegisterConnection"
	RiceSearch_ListConnections_FullMethodName    = "/ricesearch.v1.RiceSearch/ListConnections"
	RiceSearch_GetConnection_FullMethodName      = "/ricesearch.v1.RiceSearch/GetConnection"
	RiceSearch_DeleteConnection_FullMethodName   = "/ricesearch.v1.RiceSearch/DeleteConnection"
	RiceSearch_ListModels_FullMethodName         = "/ricesearch.v1.RiceSearch/ListModels"
	RiceSearch_DownloadModel_FullMethodName      = "/ricesearch.v1.RiceSearch/DownloadModel"
	RiceSearch_SetDefaultModel_FullMethodName    = "/ricesearch.v1.RiceSearch/SetDefaultModel"
	RiceSearch_ToggleGPU_FullMethodName          = "/ricesearch.v1.RiceSearch/ToggleGPU"
	RiceSearch_ListMappers_FullMethodName        = "/ricesearch.v1.RiceSearch/ListMappers"
	RiceSearch_CreateMapper_FullMethodName       = "/ricesearch.v1.RiceSearch/CreateMapper"
	RiceSearch_UpdateMapper_FullMethodName       = "/ricesearch.v1.RiceSearch/UpdateMapper"
	RiceSearch_DeleteMapper_FullMethodName       = "/ricesearch.v1.RiceSearch/DeleteMapper"
	RiceSearch_GenerateMapper_FullMethodName     = "/ricesearch.v1.RiceSearch/GenerateMapper"
	RiceSearch_ListFiles_FullMethodName          = "/ricesearch.v1.RiceSearch/ListFiles"
)

// RiceSearchClient is the client API for RiceSearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiceSearchClient interface {
	// Search performs hybrid search with optional reranking.
	// Returns a stream of results for large result sets.
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// SearchStream performs search and streams results as they're found.
	// Use this for progressive result display in UIs.
	SearchStream(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchResult], error)
	// Index indexes documents into a store.
	// Supports streaming for large batches.
	Index(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IndexRequest, IndexResponse], error)
	// IndexBatch indexes a batch of documents (non-streaming alternative).
	IndexBatch(ctx context.Context, in *IndexBatchRequest, opts ...grpc.CallOption) (*IndexResponse, error)
	// Delete removes documents from the index.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Sync removes documents that no longer exist.
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// Reindex clears and rebuilds the entire index.
	Reindex(ctx context.Context, in *ReindexRequest, opts ...grpc.CallOption) (*IndexResponse, error)
	// GetIndexStats returns indexing statistics.
	GetIndexStats(ctx context.Context, in *GetIndexStatsRequest, opts ...grpc.CallOption) (*IndexStats, error)
	// ListStores returns all stores.
	ListStores(ctx context.Context, in *ListStoresRequest, opts ...grpc.CallOption) (*ListStoresResponse, error)
	// CreateStore creates a new store.
	CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*Store, error)
	// GetStore retrieves a store by name.
	GetStore(ctx context.Context, in *GetStoreRequest, opts ...grpc.CallOption) (*Store, error)
	// DeleteStore deletes a store.
	DeleteStore(ctx context.Context, in *DeleteStoreRequest, opts ...grpc.CallOption) (*DeleteStoreResponse, error)
	// GetStoreStats returns statistics for a store.
	GetStoreStats(ctx context.Context, in *GetStoreStatsRequest, opts ...grpc.CallOption) (*StoreStats, error)
	// Health returns service health status.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Version returns version information.
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	// Connection Management
	RegisterConnection(ctx context.Context, in *RegisterConnectionRequest, opts ...grpc.CallOption) (*Connection, error)
	ListConnections(ctx context.Context, in *ListConnectionsRequest, opts ...grpc.CallOption) (*ListConnectionsResponse, error)
	GetConnection(ctx context.Context, in *GetConnectionRequest, opts ...grpc.CallOption) (*Connection, error)
	DeleteConnection(ctx context.Context, in *DeleteConnectionRequest, opts ...grpc.CallOption) (*DeleteConnectionResponse, error)
	// Model Management
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	DownloadModel(ctx context.Context, in *DownloadModelRequest, opts ...grpc.CallOption) (*DownloadModelResponse, error)
	SetDefaultModel(ctx context.Context, in *SetDefaultModelRequest, opts ...grpc.CallOption) (*ModelInfo, error)
	ToggleGPU(ctx context.Context, in *ToggleGPURequest, opts ...grpc.CallOption) (*ModelInfo, error)
	// Model Mapper Management
	ListMappers(ctx context.Context, in *ListMappersRequest, opts ...grpc.CallOption) (*ListMappersResponse, error)
	CreateMapper(ctx context.Context, in *CreateMapperRequest, opts ...grpc.CallOption) (*ModelMapper, error)
	UpdateMapper(ctx context.Context, in *UpdateMapperRequest, opts ...grpc.CallOption) (*ModelMapper, error)
	DeleteMapper(ctx context.Context, in *DeleteMapperRequest, opts ...grpc.CallOption) (*DeleteMapperResponse, error)
	GenerateMapper(ctx context.Context, in *GenerateMapperRequest, opts ...grpc.CallOption) (*ModelMapper, error)
	// File Browser
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
}

type riceSearchClient struct {
	cc grpc.ClientConnInterface
}

func NewRiceSearchClient(cc grpc.ClientConnInterface) RiceSearchClient {
	return &riceSearchClient{cc}
}

func (c *riceSearchClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, RiceSearch_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) SearchStream(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RiceSearch_ServiceDesc.Streams[0], RiceSearch_SearchStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchRequest, SearchResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RiceSearch_SearchStreamClient = grpc.ServerStreamingClient[SearchResult]

func (c *riceSearchClient) Index(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IndexRequest, IndexResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RiceSearch_ServiceDesc.Streams[1], RiceSearch_Index_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IndexRequest, IndexResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RiceSearch_IndexClient = grpc.ClientStreamingClient[IndexRequest, IndexResponse]

func (c *riceSearchClient) IndexBatch(ctx context.Context, in *IndexBatchRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexResponse)
	err := c.cc.Invoke(ctx, RiceSearch_IndexBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, RiceSearch_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, RiceSearch_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) Reindex(ctx context.Context, in *ReindexRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexResponse)
	err := c.cc.Invoke(ctx, RiceSearch_Reindex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) GetIndexStats(ctx context.Context, in *GetIndexStatsRequest, opts ...grpc.CallOption) (*IndexStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexStats)
	err := c.cc.Invoke(ctx, RiceSearch_GetIndexStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) ListStores(ctx context.Context, in *ListStoresRequest, opts ...grpc.CallOption) (*ListStoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStoresResponse)
	err := c.cc.Invoke(ctx, RiceSearch_ListStores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*Store, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Store)
	err := c.cc.Invoke(ctx, RiceSearch_CreateStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) GetStore(ctx context.Context, in *GetStoreRequest, opts ...grpc.CallOption) (*Store, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Store)
	err := c.cc.Invoke(ctx, RiceSearch_GetStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) DeleteStore(ctx context.Context, in *DeleteStoreRequest, opts ...grpc.CallOption) (*DeleteStoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStoreResponse)
	err := c.cc.Invoke(ctx, RiceSearch_DeleteStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) GetStoreStats(ctx context.Context, in *GetStoreStatsRequest, opts ...grpc.CallOption) (*StoreStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreStats)
	err := c.cc.Invoke(ctx, RiceSearch_GetStoreStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, RiceSearch_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, RiceSearch_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) RegisterConnection(ctx context.Context, in *RegisterConnectionRequest, opts ...grpc.CallOption) (*Connection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Connection)
	err := c.cc.Invoke(ctx, RiceSearch_RegisterConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) ListConnections(ctx context.Context, in *ListConnectionsRequest, opts ...grpc.CallOption) (*ListConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConnectionsResponse)
	err := c.cc.Invoke(ctx, RiceSearch_ListConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) GetConnection(ctx context.Context, in *GetConnectionRequest, opts ...grpc.CallOption) (*Connection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Connection)
	err := c.cc.Invoke(ctx, RiceSearch_GetConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) DeleteConnection(ctx context.Context, in *DeleteConnectionRequest, opts ...grpc.CallOption) (*DeleteConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConnectionResponse)
	err := c.cc.Invoke(ctx, RiceSearch_DeleteConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, RiceSearch_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) DownloadModel(ctx context.Context, in *DownloadModelRequest, opts ...grpc.CallOption) (*DownloadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadModelResponse)
	err := c.cc.Invoke(ctx, RiceSearch_DownloadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) SetDefaultModel(ctx context.Context, in *SetDefaultModelRequest, opts ...grpc.CallOption) (*ModelInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfo)
	err := c.cc.Invoke(ctx, RiceSearch_SetDefaultModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) ToggleGPU(ctx context.Context, in *ToggleGPURequest, opts ...grpc.CallOption) (*ModelInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfo)
	err := c.cc.Invoke(ctx, RiceSearch_ToggleGPU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) ListMappers(ctx context.Context, in *ListMappersRequest, opts ...grpc.CallOption) (*ListMappersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMappersResponse)
	err := c.cc.Invoke(ctx, RiceSearch_ListMappers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) CreateMapper(ctx context.Context, in *CreateMapperRequest, opts ...grpc.CallOption) (*ModelMapper, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelMapper)
	err := c.cc.Invoke(ctx, RiceSearch_CreateMapper_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) UpdateMapper(ctx context.Context, in *UpdateMapperRequest, opts ...grpc.CallOption) (*ModelMapper, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelMapper)
	err := c.cc.Invoke(ctx, RiceSearch_UpdateMapper_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) DeleteMapper(ctx context.Context, in *DeleteMapperRequest, opts ...grpc.CallOption) (*DeleteMapperResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMapperResponse)
	err := c.cc.Invoke(ctx, RiceSearch_DeleteMapper_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) GenerateMapper(ctx context.Context, in *GenerateMapperRequest, opts ...grpc.CallOption) (*ModelMapper, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelMapper)
	err := c.cc.Invoke(ctx, RiceSearch_GenerateMapper_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, RiceSearch_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiceSearchServer is the server API for RiceSearch service.
// All implementations must embed UnimplementedRiceSearchServer
// for forward compatibility.
type RiceSearchServer interface {
	// Search performs hybrid search with optional reranking.
	// Returns a stream of results for large result sets.
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// SearchStream performs search and streams results as they're found.
	// Use this for progressive result display in UIs.
	SearchStream(*SearchRequest, grpc.ServerStreamingServer[SearchResult]) error
	// Index indexes documents into a store.
	// Supports streaming for large batches.
	Index(grpc.ClientStreamingServer[IndexRequest, IndexResponse]) error
	// IndexBatch indexes a batch of documents (non-streaming alternative).
	IndexBatch(context.Context, *IndexBatchRequest) (*IndexResponse, error)
	// Delete removes documents from the index.
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// Sync removes documents that no longer exist.
	Sync(context.Context, *SyncRequest) (*SyncResponse, error)
	// Reindex clears and rebuilds the entire index.
	Reindex(context.Context, *ReindexRequest) (*IndexResponse, error)
	// GetIndexStats returns indexing statistics.
	GetIndexStats(context.Context, *GetIndexStatsRequest) (*IndexStats, error)
	// ListStores returns all stores.
	ListStores(context.Context, *ListStoresRequest) (*ListStoresResponse, error)
	// CreateStore creates a new store.
	CreateStore(context.Context, *CreateStoreRequest) (*Store, error)
	// GetStore retrieves a store by name.
	GetStore(context.Context, *GetStoreRequest) (*Store, error)
	// DeleteStore deletes a store.
	DeleteStore(context.Context, *DeleteStoreRequest) (*DeleteStoreResponse, error)
	// GetStoreStats returns statistics for a store.
	GetStoreStats(context.Context, *GetStoreStatsRequest) (*StoreStats, error)
	// Health returns service health status.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Version returns version information.
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	// Connection Management
	RegisterConnection(context.Context, *RegisterConnectionRequest) (*Connection, error)
	ListConnections(context.Context, *ListConnectionsRequest) (*ListConnectionsResponse, error)
	GetConnection(context.Context, *GetConnectionRequest) (*Connection, error)
	DeleteConnection(context.Context, *DeleteConnectionRequest) (*DeleteConnectionResponse, error)
	// Model Management
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	DownloadModel(context.Context, *DownloadModelRequest) (*DownloadModelResponse, error)
	SetDefaultModel(context.Context, *SetDefaultModelRequest) (*ModelInfo, error)
	ToggleGPU(context.Context, *ToggleGPURequest) (*ModelInfo, error)
	// Model Mapper Management
	ListMappers(context.Context, *ListMappersRequest) (*ListMappersResponse, error)
	CreateMapper(context.Context, *CreateMapperRequest) (*ModelMapper, error)
	UpdateMapper(context.Context, *UpdateMapperRequest) (*ModelMapper, error)
	DeleteMapper(context.Context, *DeleteMapperRequest) (*DeleteMapperResponse, error)
	GenerateMapper(context.Context, *GenerateMapperRequest) (*ModelMapper, error)
	// File Browser
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	mustEmbedUnimplementedRiceSearchServer()
}

// UnimplementedRiceSearchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiceSearchServer struct{}

func (UnimplementedRiceSearchServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedRiceSearchServer) SearchStream(*SearchRequest, grpc.ServerStreamingServer[SearchResult]) error {
	return status.Error(codes.Unimplemented, "method SearchStream not implemented")
}
func (UnimplementedRiceSearchServer) Index(grpc.ClientStreamingServer[IndexRequest, IndexResponse]) error {
	return status.Error(codes.Unimplemented, "method Index not implemented")
}
func (UnimplementedRiceSearchServer) IndexBatch(context.Context, *IndexBatchRequest) (*IndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexBatch not implemented")
}
func (UnimplementedRiceSearchServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRiceSearchServer) Sync(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedRiceSearchServer) Reindex(context.Context, *ReindexRequest) (*IndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reindex not implemented")
}
func (UnimplementedRiceSearchServer) GetIndexStats(context.Context, *GetIndexStatsRequest) (*IndexStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIndexStats not implemented")
}
func (UnimplementedRiceSearchServer) ListStores(context.Context, *ListStoresRequest) (*ListStoresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStores not implemented")
}
func (UnimplementedRiceSearchServer) CreateStore(context.Context, *CreateStoreRequest) (*Store, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStore not implemented")
}
func (UnimplementedRiceSearchServer) GetStore(context.Context, *GetStoreRequest) (*Store, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStore not implemented")
}
func (UnimplementedRiceSearchServer) DeleteStore(context.Context, *DeleteStoreRequest) (*DeleteStoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteStore not implemented")
}
func (UnimplementedRiceSearchServer) GetStoreStats(context.Context, *GetStoreStatsRequest) (*StoreStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStoreStats not implemented")
}
func (UnimplementedRiceSearchServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedRiceSearchServer) Version(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedRiceSearchServer) RegisterConnection(context.Context, *RegisterConnectionRequest) (*Connection, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterConnection not implemented")
}
func (UnimplementedRiceSearchServer) ListConnections(context.Context, *ListConnectionsRequest) (*ListConnectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConnections not implemented")
}
func (UnimplementedRiceSearchServer) GetConnection(context.Context, *GetConnectionRequest) (*Connection, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnection not implemented")
}
func (UnimplementedRiceSearchServer) DeleteConnection(context.Context, *DeleteConnectionRequest) (*DeleteConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConnection not implemented")
}
func (UnimplementedRiceSearchServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedRiceSearchServer) DownloadModel(context.Context, *DownloadModelRequest) (*DownloadModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadModel not implemented")
}
func (UnimplementedRiceSearchServer) SetDefaultModel(context.Context, *SetDefaultModelRequest) (*ModelInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDefaultModel not implemented")
}
func (UnimplementedRiceSearchServer) ToggleGPU(context.Context, *ToggleGPURequest) (*ModelInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleGPU not implemented")
}
func (UnimplementedRiceSearchServer) ListMappers(context.Context, *ListMappersRequest) (*ListMappersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMappers not implemented")
}
func (UnimplementedRiceSearchServer) CreateMapper(context.Context, *CreateMapperRequest) (*ModelMapper, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMapper not implemented")
}
func (UnimplementedRiceSearchServer) UpdateMapper(context.Context, *UpdateMapperRequest) (*ModelMapper, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMapper not implemented")
}
func (UnimplementedRiceSearchServer) DeleteMapper(context.Context, *DeleteMapperRequest) (*DeleteMapperResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMapper not implemented")
}
func (UnimplementedRiceSearchServer) GenerateMapper(context.Context, *GenerateMapperRequest) (*ModelMapper, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateMapper not implemented")
}
func (UnimplementedRiceSearchServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedRiceSearchServer) mustEmbedUnimplementedRiceSearchServer() {}
func (UnimplementedRiceSearchServer) testEmbeddedByValue()                    {}

// UnsafeRiceSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiceSearchServer will
// result in compilation errors.
type UnsafeRiceSearchServer interface {
	mustEmbedUnimplementedRiceSearchServer()
}

func RegisterRiceSearchServer(s grpc.ServiceRegistrar, srv RiceSearchServer) {
	// If the following call panics, it indicates UnimplementedRiceSearchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiceSearch_ServiceDesc, srv)
}

func _RiceSearch_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_SearchStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RiceSearchServer).SearchStream(m, &grpc.GenericServerStream[SearchRequest, SearchResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RiceSearch_SearchStreamServer = grpc.ServerStreamingServer[SearchResult]

func _RiceSearch_Index_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RiceSearchServer).Index(&grpc.GenericServerStream[IndexRequest, IndexResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RiceSearch_IndexServer = grpc.ClientStreamingServer[IndexRequest, IndexResponse]

func _RiceSearch_IndexBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).IndexBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_IndexBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).IndexBatch(ctx, req.(*IndexBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_Reindex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReindexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).Reindex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_Reindex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).Reindex(ctx, req.(*ReindexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_GetIndexStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).GetIndexStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_GetIndexStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).GetIndexStats(ctx, req.(*GetIndexStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_ListStores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).ListStores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_ListStores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).ListStores(ctx, req.(*ListStoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_CreateStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).CreateStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_CreateStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).CreateStore(ctx, req.(*CreateStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_GetStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).GetStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_GetStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).GetStore(ctx, req.(*GetStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_DeleteStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).DeleteStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_DeleteStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).DeleteStore(ctx, req.(*DeleteStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_GetStoreStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoreStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).GetStoreStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_GetStoreStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).GetStoreStats(ctx, req.(*GetStoreStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_RegisterConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).RegisterConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_RegisterConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).RegisterConnection(ctx, req.(*RegisterConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_ListConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).ListConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_ListConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).ListConnections(ctx, req.(*ListConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_GetConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).GetConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_GetConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).GetConnection(ctx, req.(*GetConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_DeleteConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).DeleteConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_DeleteConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).DeleteConnection(ctx, req.(*DeleteConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_DownloadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).DownloadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_DownloadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).DownloadModel(ctx, req.(*DownloadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_SetDefaultModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).SetDefaultModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_SetDefaultModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).SetDefaultModel(ctx, req.(*SetDefaultModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_ToggleGPU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleGPURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).ToggleGPU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_ToggleGPU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).ToggleGPU(ctx, req.(*ToggleGPURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_ListMappers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMappersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).ListMappers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_ListMappers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).ListMappers(ctx, req.(*ListMappersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_CreateMapper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMapperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).CreateMapper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_CreateMapper_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).CreateMapper(ctx, req.(*CreateMapperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_UpdateMapper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMapperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).UpdateMapper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_UpdateMapper_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).UpdateMapper(ctx, req.(*UpdateMapperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_DeleteMapper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMapperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).DeleteMapper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_DeleteMapper_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).DeleteMapper(ctx, req.(*DeleteMapperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_GenerateMapper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateMapperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).GenerateMapper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_GenerateMapper_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).GenerateMapper(ctx, req.(*GenerateMapperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiceSearch_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiceSearch_ServiceDesc is the grpc.ServiceDesc for RiceSearch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiceSearch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ricesearch.v1.RiceSearch",
	HandlerType: (*RiceSearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _RiceSearch_Search_Handler,
		},
		{
			MethodName: "IndexBatch",
			Handler:    _RiceSearch_IndexBatch_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RiceSearch_Delete_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _RiceSearch_Sync_Handler,
		},
		{
			MethodName: "Reindex",
			Handler:    _RiceSearch_Reindex_Handler,
		},
		{
			MethodName: "GetIndexStats",
			Handler:    _RiceSearch_GetIndexStats_Handler,
		},
		{
			MethodName: "ListStores",
			Handler:    _RiceSearch_ListStores_Handler,
		},
		{
			MethodName: "CreateStore",
			Handler:    _RiceSearch_CreateStore_Handler,
		},
		{
			MethodName: "GetStore",
			Handler:    _RiceSearch_GetStore_Handler,
		},
		{
			MethodName: "DeleteStore",
			Handler:    _RiceSearch_DeleteStore_Handler,
		},
		{
			MethodName: "GetStoreStats",
			Handler:    _RiceSearch_GetStoreStats_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _RiceSearch_Health_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _RiceSearch_Version_Handler,
		},
		{
			MethodName: "RegisterConnection",
			Handler:    _RiceSearch_RegisterConnection_Handler,
		},
		{
			MethodName: "ListConnections",
			Handler:    _RiceSearch_ListConnections_Handler,
		},
		{
			MethodName: "GetConnection",
			Handler:    _RiceSearch_GetConnection_Handler,
		},
		{
			MethodName: "DeleteConnection",
			Handler:    _RiceSearch_DeleteConnection_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _RiceSearch_ListModels_Handler,
		},
		{
			MethodName: "DownloadModel",
			Handler:    _RiceSearch_DownloadModel_Handler,
		},
		{
			MethodName: "SetDefaultModel",
			Handler:    _RiceSearch_SetDefaultModel_Handler,
		},
		{
			MethodName: "ToggleGPU",
			Handler:    _RiceSearch_ToggleGPU_Handler,
		},
		{
			MethodName: "ListMappers",
			Handler:    _RiceSearch_ListMappers_Handler,
		},
		{
			MethodName: "CreateMapper",
			Handler:    _RiceSearch_CreateMapper_Handler,
		},
		{
			MethodName: "UpdateMapper",
			Handler:    _RiceSearch_UpdateMapper_Handler,
		},
		{
			MethodName: "DeleteMapper",
			Handler:    _RiceSearch_DeleteMapper_Handler,
		},
		{
			MethodName: "GenerateMapper",
			Handler:    _RiceSearch_GenerateMapper_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _RiceSearch_ListFiles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchStream",
			Handler:       _RiceSearch_SearchStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Index",
			Handler:       _RiceSearch_Index_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "ricesearch.proto",
}
