// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: ricesearch.proto

package ricesearchpb

import (
	"context"
	"io"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// RiceSearchClient is the client API for RiceSearch service.
type RiceSearchClient interface {
	// Search performs hybrid search with optional reranking.
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// SearchStream performs search and streams results.
	SearchStream(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (RiceSearch_SearchStreamClient, error)
	// Index indexes documents (streaming).
	Index(ctx context.Context, opts ...grpc.CallOption) (RiceSearch_IndexClient, error)
	// IndexBatch indexes a batch of documents.
	IndexBatch(ctx context.Context, in *IndexBatchRequest, opts ...grpc.CallOption) (*IndexResponse, error)
	// Delete removes documents from the index.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Sync removes documents that no longer exist.
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// Reindex clears and rebuilds the entire index.
	Reindex(ctx context.Context, in *ReindexRequest, opts ...grpc.CallOption) (*IndexResponse, error)
	// GetIndexStats returns indexing statistics.
	GetIndexStats(ctx context.Context, in *GetIndexStatsRequest, opts ...grpc.CallOption) (*IndexStats, error)
	// ListStores returns all stores.
	ListStores(ctx context.Context, in *ListStoresRequest, opts ...grpc.CallOption) (*ListStoresResponse, error)
	// CreateStore creates a new store.
	CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*Store, error)
	// GetStore retrieves a store by name.
	GetStore(ctx context.Context, in *GetStoreRequest, opts ...grpc.CallOption) (*Store, error)
	// DeleteStore deletes a store.
	DeleteStore(ctx context.Context, in *DeleteStoreRequest, opts ...grpc.CallOption) (*DeleteStoreResponse, error)
	// GetStoreStats returns statistics for a store.
	GetStoreStats(ctx context.Context, in *GetStoreStatsRequest, opts ...grpc.CallOption) (*StoreStats, error)
	// Health returns service health status.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Version returns version information.
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	// Connection Management
	RegisterConnection(ctx context.Context, in *RegisterConnectionRequest, opts ...grpc.CallOption) (*Connection, error)
	ListConnections(ctx context.Context, in *ListConnectionsRequest, opts ...grpc.CallOption) (*ListConnectionsResponse, error)
	GetConnection(ctx context.Context, in *GetConnectionRequest, opts ...grpc.CallOption) (*Connection, error)
	DeleteConnection(ctx context.Context, in *DeleteConnectionRequest, opts ...grpc.CallOption) (*DeleteConnectionResponse, error)
	// Model Management
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	DownloadModel(ctx context.Context, in *DownloadModelRequest, opts ...grpc.CallOption) (*DownloadModelResponse, error)
	SetDefaultModel(ctx context.Context, in *SetDefaultModelRequest, opts ...grpc.CallOption) (*ModelInfo, error)
	ToggleGPU(ctx context.Context, in *ToggleGPURequest, opts ...grpc.CallOption) (*ModelInfo, error)
	// Model Mapper Management
	ListMappers(ctx context.Context, in *ListMappersRequest, opts ...grpc.CallOption) (*ListMappersResponse, error)
	CreateMapper(ctx context.Context, in *CreateMapperRequest, opts ...grpc.CallOption) (*ModelMapper, error)
	UpdateMapper(ctx context.Context, in *UpdateMapperRequest, opts ...grpc.CallOption) (*ModelMapper, error)
	DeleteMapper(ctx context.Context, in *DeleteMapperRequest, opts ...grpc.CallOption) (*DeleteMapperResponse, error)
	GenerateMapper(ctx context.Context, in *GenerateMapperRequest, opts ...grpc.CallOption) (*ModelMapper, error)
	// File Browser
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
}

type riceSearchClient struct {
	cc grpc.ClientConnInterface
}

// NewRiceSearchClient creates a new RiceSearch client.
func NewRiceSearchClient(cc grpc.ClientConnInterface) RiceSearchClient {
	return &riceSearchClient{cc}
}

func (c *riceSearchClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiceSearch_SearchStreamClient is the client stream for SearchStream.
type RiceSearch_SearchStreamClient interface {
	Recv() (*SearchResult, error)
	grpc.ClientStream
}

type riceSearchSearchStreamClient struct {
	grpc.ClientStream
}

func (x *riceSearchSearchStreamClient) Recv() (*SearchResult, error) {
	m := new(SearchResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *riceSearchClient) SearchStream(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (RiceSearch_SearchStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &RiceSearch_ServiceDesc.Streams[0], "/ricesearch.v1.RiceSearch/SearchStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &riceSearchSearchStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// RiceSearch_IndexClient is the client stream for Index.
type RiceSearch_IndexClient interface {
	Send(*IndexRequest) error
	CloseAndRecv() (*IndexResponse, error)
	grpc.ClientStream
}

type riceSearchIndexClient struct {
	grpc.ClientStream
}

func (x *riceSearchIndexClient) Send(m *IndexRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *riceSearchIndexClient) CloseAndRecv() (*IndexResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(IndexResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *riceSearchClient) Index(ctx context.Context, opts ...grpc.CallOption) (RiceSearch_IndexClient, error) {
	stream, err := c.cc.NewStream(ctx, &RiceSearch_ServiceDesc.Streams[1], "/ricesearch.v1.RiceSearch/Index", opts...)
	if err != nil {
		return nil, err
	}
	return &riceSearchIndexClient{stream}, nil
}

func (c *riceSearchClient) IndexBatch(ctx context.Context, in *IndexBatchRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	out := new(IndexResponse)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/IndexBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/Sync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) Reindex(ctx context.Context, in *ReindexRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	out := new(IndexResponse)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/Reindex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) GetIndexStats(ctx context.Context, in *GetIndexStatsRequest, opts ...grpc.CallOption) (*IndexStats, error) {
	out := new(IndexStats)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/GetIndexStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) ListStores(ctx context.Context, in *ListStoresRequest, opts ...grpc.CallOption) (*ListStoresResponse, error) {
	out := new(ListStoresResponse)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/ListStores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*Store, error) {
	out := new(Store)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/CreateStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) GetStore(ctx context.Context, in *GetStoreRequest, opts ...grpc.CallOption) (*Store, error) {
	out := new(Store)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/GetStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) DeleteStore(ctx context.Context, in *DeleteStoreRequest, opts ...grpc.CallOption) (*DeleteStoreResponse, error) {
	out := new(DeleteStoreResponse)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/DeleteStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) GetStoreStats(ctx context.Context, in *GetStoreStatsRequest, opts ...grpc.CallOption) (*StoreStats, error) {
	out := new(StoreStats)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/GetStoreStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Connection Management
func (c *riceSearchClient) RegisterConnection(ctx context.Context, in *RegisterConnectionRequest, opts ...grpc.CallOption) (*Connection, error) {
	out := new(Connection)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/RegisterConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) ListConnections(ctx context.Context, in *ListConnectionsRequest, opts ...grpc.CallOption) (*ListConnectionsResponse, error) {
	out := new(ListConnectionsResponse)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/ListConnections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) GetConnection(ctx context.Context, in *GetConnectionRequest, opts ...grpc.CallOption) (*Connection, error) {
	out := new(Connection)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/GetConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) DeleteConnection(ctx context.Context, in *DeleteConnectionRequest, opts ...grpc.CallOption) (*DeleteConnectionResponse, error) {
	out := new(DeleteConnectionResponse)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/DeleteConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Model Management
func (c *riceSearchClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/ListModels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) DownloadModel(ctx context.Context, in *DownloadModelRequest, opts ...grpc.CallOption) (*DownloadModelResponse, error) {
	out := new(DownloadModelResponse)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/DownloadModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) SetDefaultModel(ctx context.Context, in *SetDefaultModelRequest, opts ...grpc.CallOption) (*ModelInfo, error) {
	out := new(ModelInfo)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/SetDefaultModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) ToggleGPU(ctx context.Context, in *ToggleGPURequest, opts ...grpc.CallOption) (*ModelInfo, error) {
	out := new(ModelInfo)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/ToggleGPU", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Model Mapper Management
func (c *riceSearchClient) ListMappers(ctx context.Context, in *ListMappersRequest, opts ...grpc.CallOption) (*ListMappersResponse, error) {
	out := new(ListMappersResponse)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/ListMappers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) CreateMapper(ctx context.Context, in *CreateMapperRequest, opts ...grpc.CallOption) (*ModelMapper, error) {
	out := new(ModelMapper)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/CreateMapper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) UpdateMapper(ctx context.Context, in *UpdateMapperRequest, opts ...grpc.CallOption) (*ModelMapper, error) {
	out := new(ModelMapper)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/UpdateMapper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) DeleteMapper(ctx context.Context, in *DeleteMapperRequest, opts ...grpc.CallOption) (*DeleteMapperResponse, error) {
	out := new(DeleteMapperResponse)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/DeleteMapper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riceSearchClient) GenerateMapper(ctx context.Context, in *GenerateMapperRequest, opts ...grpc.CallOption) (*ModelMapper, error) {
	out := new(ModelMapper)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/GenerateMapper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// File Browser
func (c *riceSearchClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, "/ricesearch.v1.RiceSearch/ListFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiceSearchServer is the server API for RiceSearch service.
type RiceSearchServer interface {
	// Search performs hybrid search with optional reranking.
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// SearchStream performs search and streams results.
	SearchStream(*SearchRequest, RiceSearch_SearchStreamServer) error
	// Index indexes documents (streaming).
	Index(RiceSearch_IndexServer) error
	// IndexBatch indexes a batch of documents.
	IndexBatch(context.Context, *IndexBatchRequest) (*IndexResponse, error)
	// Delete removes documents from the index.
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// Sync removes documents that no longer exist.
	Sync(context.Context, *SyncRequest) (*SyncResponse, error)
	// Reindex clears and rebuilds the entire index.
	Reindex(context.Context, *ReindexRequest) (*IndexResponse, error)
	// GetIndexStats returns indexing statistics.
	GetIndexStats(context.Context, *GetIndexStatsRequest) (*IndexStats, error)
	// ListStores returns all stores.
	ListStores(context.Context, *ListStoresRequest) (*ListStoresResponse, error)
	// CreateStore creates a new store.
	CreateStore(context.Context, *CreateStoreRequest) (*Store, error)
	// GetStore retrieves a store by name.
	GetStore(context.Context, *GetStoreRequest) (*Store, error)
	// DeleteStore deletes a store.
	DeleteStore(context.Context, *DeleteStoreRequest) (*DeleteStoreResponse, error)
	// GetStoreStats returns statistics for a store.
	GetStoreStats(context.Context, *GetStoreStatsRequest) (*StoreStats, error)
	// Health returns service health status.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Version returns version information.
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	// Connection Management
	RegisterConnection(context.Context, *RegisterConnectionRequest) (*Connection, error)
	ListConnections(context.Context, *ListConnectionsRequest) (*ListConnectionsResponse, error)
	GetConnection(context.Context, *GetConnectionRequest) (*Connection, error)
	DeleteConnection(context.Context, *DeleteConnectionRequest) (*DeleteConnectionResponse, error)
	// Model Management
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	DownloadModel(context.Context, *DownloadModelRequest) (*DownloadModelResponse, error)
	SetDefaultModel(context.Context, *SetDefaultModelRequest) (*ModelInfo, error)
	ToggleGPU(context.Context, *ToggleGPURequest) (*ModelInfo, error)
	// Model Mapper Management
	ListMappers(context.Context, *ListMappersRequest) (*ListMappersResponse, error)
	CreateMapper(context.Context, *CreateMapperRequest) (*ModelMapper, error)
	UpdateMapper(context.Context, *UpdateMapperRequest) (*ModelMapper, error)
	DeleteMapper(context.Context, *DeleteMapperRequest) (*DeleteMapperResponse, error)
	GenerateMapper(context.Context, *GenerateMapperRequest) (*ModelMapper, error)
	// File Browser
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	mustEmbedUnimplementedRiceSearchServer()
}

// UnimplementedRiceSearchServer must be embedded for forward compatibility.
type UnimplementedRiceSearchServer struct{}

func (UnimplementedRiceSearchServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedRiceSearchServer) SearchStream(*SearchRequest, RiceSearch_SearchStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchStream not implemented")
}
func (UnimplementedRiceSearchServer) Index(RiceSearch_IndexServer) error {
	return status.Errorf(codes.Unimplemented, "method Index not implemented")
}
func (UnimplementedRiceSearchServer) IndexBatch(context.Context, *IndexBatchRequest) (*IndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndexBatch not implemented")
}
func (UnimplementedRiceSearchServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRiceSearchServer) Sync(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedRiceSearchServer) Reindex(context.Context, *ReindexRequest) (*IndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reindex not implemented")
}
func (UnimplementedRiceSearchServer) GetIndexStats(context.Context, *GetIndexStatsRequest) (*IndexStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIndexStats not implemented")
}
func (UnimplementedRiceSearchServer) ListStores(context.Context, *ListStoresRequest) (*ListStoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStores not implemented")
}
func (UnimplementedRiceSearchServer) CreateStore(context.Context, *CreateStoreRequest) (*Store, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStore not implemented")
}
func (UnimplementedRiceSearchServer) GetStore(context.Context, *GetStoreRequest) (*Store, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStore not implemented")
}
func (UnimplementedRiceSearchServer) DeleteStore(context.Context, *DeleteStoreRequest) (*DeleteStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStore not implemented")
}
func (UnimplementedRiceSearchServer) GetStoreStats(context.Context, *GetStoreStatsRequest) (*StoreStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStoreStats not implemented")
}
func (UnimplementedRiceSearchServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedRiceSearchServer) Version(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}

// Connection Management
func (UnimplementedRiceSearchServer) RegisterConnection(context.Context, *RegisterConnectionRequest) (*Connection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterConnection not implemented")
}
func (UnimplementedRiceSearchServer) ListConnections(context.Context, *ListConnectionsRequest) (*ListConnectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConnections not implemented")
}
func (UnimplementedRiceSearchServer) GetConnection(context.Context, *GetConnectionRequest) (*Connection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnection not implemented")
}
func (UnimplementedRiceSearchServer) DeleteConnection(context.Context, *DeleteConnectionRequest) (*DeleteConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConnection not implemented")
}

// Model Management
func (UnimplementedRiceSearchServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedRiceSearchServer) DownloadModel(context.Context, *DownloadModelRequest) (*DownloadModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadModel not implemented")
}
func (UnimplementedRiceSearchServer) SetDefaultModel(context.Context, *SetDefaultModelRequest) (*ModelInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDefaultModel not implemented")
}
func (UnimplementedRiceSearchServer) ToggleGPU(context.Context, *ToggleGPURequest) (*ModelInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleGPU not implemented")
}

// Model Mapper Management
func (UnimplementedRiceSearchServer) ListMappers(context.Context, *ListMappersRequest) (*ListMappersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMappers not implemented")
}
func (UnimplementedRiceSearchServer) CreateMapper(context.Context, *CreateMapperRequest) (*ModelMapper, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMapper not implemented")
}
func (UnimplementedRiceSearchServer) UpdateMapper(context.Context, *UpdateMapperRequest) (*ModelMapper, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMapper not implemented")
}
func (UnimplementedRiceSearchServer) DeleteMapper(context.Context, *DeleteMapperRequest) (*DeleteMapperResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMapper not implemented")
}
func (UnimplementedRiceSearchServer) GenerateMapper(context.Context, *GenerateMapperRequest) (*ModelMapper, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateMapper not implemented")
}

// File Browser
func (UnimplementedRiceSearchServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}

func (UnimplementedRiceSearchServer) mustEmbedUnimplementedRiceSearchServer() {}

// UnsafeRiceSearchServer may be embedded to opt out of forward compatibility.
type UnsafeRiceSearchServer interface {
	mustEmbedUnimplementedRiceSearchServer()
}

// RiceSearch_SearchStreamServer is the server stream for SearchStream.
type RiceSearch_SearchStreamServer interface {
	Send(*SearchResult) error
	grpc.ServerStream
}

type riceSearchSearchStreamServer struct {
	grpc.ServerStream
}

func (x *riceSearchSearchStreamServer) Send(m *SearchResult) error {
	return x.ServerStream.SendMsg(m)
}

// RiceSearch_IndexServer is the server stream for Index.
type RiceSearch_IndexServer interface {
	SendAndClose(*IndexResponse) error
	Recv() (*IndexRequest, error)
	grpc.ServerStream
}

type riceSearchIndexServer struct {
	grpc.ServerStream
}

func (x *riceSearchIndexServer) SendAndClose(m *IndexResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *riceSearchIndexServer) Recv() (*IndexRequest, error) {
	m := new(IndexRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RiceSearch_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ricesearch.v1.RiceSearch/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_SearchStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RiceSearchServer).SearchStream(m, &riceSearchSearchStreamServer{stream})
}

func _RiceSearch_Index_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RiceSearchServer).Index(&riceSearchIndexServer{stream})
}

func _RiceSearch_IndexBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).IndexBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ricesearch.v1.RiceSearch/IndexBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).IndexBatch(ctx, req.(*IndexBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ricesearch.v1.RiceSearch/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ricesearch.v1.RiceSearch/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_Reindex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReindexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).Reindex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ricesearch.v1.RiceSearch/Reindex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).Reindex(ctx, req.(*ReindexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_GetIndexStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).GetIndexStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ricesearch.v1.RiceSearch/GetIndexStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).GetIndexStats(ctx, req.(*GetIndexStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_ListStores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).ListStores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ricesearch.v1.RiceSearch/ListStores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).ListStores(ctx, req.(*ListStoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_CreateStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).CreateStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ricesearch.v1.RiceSearch/CreateStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).CreateStore(ctx, req.(*CreateStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_GetStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).GetStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ricesearch.v1.RiceSearch/GetStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).GetStore(ctx, req.(*GetStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_DeleteStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).DeleteStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ricesearch.v1.RiceSearch/DeleteStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).DeleteStore(ctx, req.(*DeleteStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_GetStoreStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoreStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).GetStoreStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ricesearch.v1.RiceSearch/GetStoreStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).GetStoreStats(ctx, req.(*GetStoreStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ricesearch.v1.RiceSearch/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiceSearch_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiceSearchServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ricesearch.v1.RiceSearch/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiceSearchServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiceSearch_ServiceDesc is the grpc.ServiceDesc for RiceSearch service.
var RiceSearch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ricesearch.v1.RiceSearch",
	HandlerType: (*RiceSearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _RiceSearch_Search_Handler,
		},
		{
			MethodName: "IndexBatch",
			Handler:    _RiceSearch_IndexBatch_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RiceSearch_Delete_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _RiceSearch_Sync_Handler,
		},
		{
			MethodName: "Reindex",
			Handler:    _RiceSearch_Reindex_Handler,
		},
		{
			MethodName: "GetIndexStats",
			Handler:    _RiceSearch_GetIndexStats_Handler,
		},
		{
			MethodName: "ListStores",
			Handler:    _RiceSearch_ListStores_Handler,
		},
		{
			MethodName: "CreateStore",
			Handler:    _RiceSearch_CreateStore_Handler,
		},
		{
			MethodName: "GetStore",
			Handler:    _RiceSearch_GetStore_Handler,
		},
		{
			MethodName: "DeleteStore",
			Handler:    _RiceSearch_DeleteStore_Handler,
		},
		{
			MethodName: "GetStoreStats",
			Handler:    _RiceSearch_GetStoreStats_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _RiceSearch_Health_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _RiceSearch_Version_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchStream",
			Handler:       _RiceSearch_SearchStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Index",
			Handler:       _RiceSearch_Index_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "ricesearch.proto",
}

// RegisterRiceSearchServer registers a RiceSearchServer with the gRPC server.
func RegisterRiceSearchServer(s grpc.ServiceRegistrar, srv RiceSearchServer) {
	s.RegisterService(&RiceSearch_ServiceDesc, srv)
}

// Helper function to drain Index stream
func DrainIndexStream(stream RiceSearch_IndexServer) ([]*IndexRequest, error) {
	var requests []*IndexRequest
	for {
		req, err := stream.Recv()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}
		requests = append(requests, req)
	}
	return requests, nil
}
